### PR TITLE
Refactor EntityManager injections to avoid conflict between WidgetCss command and WidgetMapDataWarmer

### PR DESCRIPTION
**Pull request by gregumo**

### CODE REVIEW

**Comment by paulandrieux** [comment]
The WidgetMapManipulator class name seems too generic, I would préfère something like "WidgetPositionComputer", what do you think @leny

**Comment by leny** [comment]
I don't know why I'm being mentionned here. Probably a typo?

**Comment by talbotseb** [comment]
@leny this is a mistake from @paulandrieux who wanted to mention @lenybernard the Lead Dev of Victoire's project. Sorry for this :)

**Comment by leny** [comment]
No problem. Glad it's just a typo, I'm not very good at naming things. :smiley:

**Comment by talbotseb** [comment]
:+1: You've been saved !

**Pull request merged**
