### PR TITLE
CircleCI: Use PHP 7.1.9, avoid bug with doctrine/orm 2.6

### PR DESCRIPTION
**Pull request by alexislefebvre**
## Type
Feature

## Purpose
Upgrade version of PHP used on CircleCI.

## BC Break
NO

Same as #1022.

### CODE REVIEW

**Comment by alexislefebvre** [comment]
I rebased this branch on 2.3, so the only changes here are related to the upgrade to PHP 7.1.9 on CircleCI and that make tests break. It looks like PHP 7.1 break the selection of a parent page when modifying a template, among other things.

**Comment by alexislefebvre** [comment]
I installed dependencies for PHP 7.0 instead of PHP 7.1:

```
"config" : {
        "platform": {
            "php": "7.0"
        }
    },
```

It fixes the problem related to the Parent page. It looks like one library installed with PHP 7.1 causes some trouble. I'll try to find which dependency make tests to fail.

**Comment by alexislefebvre** [comment]
It looks like using `doctrine/orm` 2.5 instead of 2.6 fixes some issues.

**Comment by alexislefebvre** [comment]
The tests CircleCI passed to green again once I limited `doctrine/orm` to the 2.5 version! :tada:

So, it looks like Victoire does no work with ORM 2.6, I have the feeling that all the inheritance with views, templates, etc. doesn't work as expected. Maybe it only requires a small tweak in the entity configurations to fix that problem.

@Victoire/core-team Should we merge this PR as is, or should we work on the incompatibility with ORM 2.6? Thanks.

**Comment by lenybernard** [comment]
Closed in favor of #1028

**Pull request closed without merging**
