### PR TITLE
Fix issues with sensio/framework-extra-bundle 4.0+

### LINKED ISSUE #1043: Installation fails on sensio/framework-extra-bundle dependency
## Description
Victoire fails to install when following official installation guide. Issuing the command:
```
composer require victoire/victoire twig/twig:~2.0
```
on clean Symfony 3.4 fails with error message:

```
Using version ^2.3 for victoire/victoire
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - victoire/victoire 2.3.9 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.8 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.7 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.6 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.5 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.4 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.3 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.29 requires sensio/framework-extra-bundle ^3.0.2 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.28 requires sensio/framework-extra-bundle ^3.0.2 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.27 requires sensio/framework-extra-bundle ^3.0.2 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.26 requires sensio/framework-extra-bundle ^3.0.2 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.25 requires sensio/framework-extra-bundle ^3.0.2 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.24 requires sensio/framework-extra-bundle ^3.0.2 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.23 requires sensio/framework-extra-bundle ^3.0.2 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.22 requires sensio/framework-extra-bundle ^3.0.2 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.21 requires sensio/framework-extra-bundle ^3.0.2 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.20 requires sensio/framework-extra-bundle ^3.0.2 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.2 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.19 requires sensio/framework-extra-bundle ^3.0.2 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.18 requires sensio/framework-extra-bundle ^3.0.2 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.17 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.16 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.15 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.14 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.13 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.12 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.11 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.10 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.1 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - victoire/victoire 2.3.0 requires sensio/framework-extra-bundle ~3.0 -> satisfiable by sensio/framework-extra-bundle[3.0.x-dev, v3.0.0, v3.0.1, v3.0.10, v3.0.11, v3.0.12, v3.0.13, v3.0.14, v3.0.15, v3.0.16, v3.0.17, v3.0.18, v3.0.19, v3.0.2, v3.0.20, v3.0.21, v3.0.22, v3.0.23, v3.0.24, v3.0.25, v3.0.26, v3.0.27, v3.0.28, v3.0.29, v3.0.3, v3.0.4, v3.0.5, v3.0.6, v3.0.7, v3.0.8, v3.0.9] but these conflict with your requirements or minimum-stability.
    - Installation request for victoire/victoire ^2.3 -> satisfiable by victoire/victoire[2.3.0, 2.3.1, 2.3.10, 2.3.11, 2.3.12, 2.3.13, 2.3.14, 2.3.15, 2.3.16, 2.3.17, 2.3.18, 2.3.19, 2.3.2, 2.3.20, 2.3.21, 2.3.22, 2.3.23, 2.3.24, 2.3.25, 2.3.26, 2.3.27, 2.3.28, 2.3.29, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9].


Installation failed, reverting ./composer.json to its original content.
```

### PR DESCRIPTION
**Pull request by alexislefebvre**
## Type
Bugfix

## Purpose
Fixes #1043: incompatibility between Victoire 2.3 and Symfony 3.4

## BC Break
YES, since sensio/framework-extra-bundle 4.0 breaks how paths to Twig files are generated:

> [BC BREAK] changed template name generation from camelCase to under_score for both files and directories

Source: https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/445e0d9e2603de2a0c627f50bc7069daf5dfb0f3/CHANGELOG.md#40

### CODE REVIEW

**Comment by alexislefebvre** [comment]
Rebased on #1042 to avoid failing tests.

**Comment by alexislefebvre** [comment]
I ran some tests that failed in https://circleci.com/gh/Victoire/victoire/1450 and they worked on my local environment.

Tests failed on the lastest build of the 2.3 branch: https://circleci.com/gh/Victoire/victoire/1449

It's still unclear if tests are broken because of this PR or the 2.3 branch.

Unfortunately, the build on CircleCI is stuck: https://circleci.com/gh/Victoire/victoire/1450

**Comment by alexislefebvre** [comment]
One error is `Unable to find template "@AcmeApp/jedi/index.html.twig" (looked into: /home/alexis/works/victoire/Tests/App/src/Acme/AppBundle/Resources/views).`. It looks like `framework-extra-bundle` has changed how case is managed in template files.

**Comment by alexislefebvre** [comment]
@Victoire/core-team This PR introduces a BC break, it will break controllers that use the  `@Controller` annotation without providing a path.

Ideally we should publish a 3.0 release, but we should wait to have more BC break changes.

We can also forget semver and publish a 2.4 release with this change.

**Comment by alexislefebvre** [comment]
On the other hand, we require a newer version of a dependency, this will generate conflicts in existing projects so users will have to update their version of SensioFrameworkExtraBundle and take care of BC break from this bundle. And the fixes are easy to apply.

I think that we can merge it in the current branch of Victoire without releasing a major version.

I'll add a note in the CHANGELOG.

**Comment by lenybernard** [comment]
thank you @alexislefebvre !

**Pull request merged**
