### PR TITLE
[WIP] Compatibility with symfony 3.2.10

### LINKED ISSUE #951: Compatibility with symfony 3.2.10
## Description
The version 3.2.10 of `symfony/symfony` makes victoire crash. 

## Temporary resolution
Fix the `"symfony/symfony": "3.2.9"` version in you project's composer.json

## Resolution Ideas
I don't know yet what between [v3.2.9...v3.2.10 ](https://github.com/symfony/symfony/compare/v3.2.9...v3.2.10) fucked victoire. 👀

## Related to

| Bundle         |    --    | --             | --       |
| -------------- |:--------:| --             | --       |
| Analytics      |  | Page           |  |
| Blog           |          | Query          |          |
| BusinessEntity |          |Seo             |          |
| BusinessPage   |          | Sitemap        |          |
| Core           |  &#10004; | Template       |          |
| Criteria       |          | Twig           |          |
| Filter         |          | User           |          |
| Form           |          | ViewReference  |          |
| I18n           |          | Widget         |          |
| Media          |          | WidgetMap      |          |
| UI             |          |                |          |

### PR DESCRIPTION
**Pull request by Yoann-TYT**
I suggest using tokenizer instead of get_declared_classes
 I think that the function getClassNameFromFile should be tested

## Type
Bugfix

## Purpose

Fixes #951

## BC Break
YES|NO

This PR breaks (this|that)

### CODE REVIEW

**Comment by lenybernard** [comment]
Hello @Yoann-TYT 

Thank you for your effort, can you tell us what you learned about this problem so we'll be able to continue your job ?

**Comment by Yoann-TYT** [comment]
Hi Leny !
I suggest you to read my first commit. 
In fact, it solves the problem... but I've got another fails ( that you can see on CircleCI ).
When you do a cache:warmup, before upgrading Symfony, the method that you use, get_declared_class, should return the needed classes. 
After a few tests, the problem seems coming from issue #23014 of Symfony ( merged in 3.2.10 ). 
So I tried to change get_declared_classes by an another method... But unfortunately, it doesn't work ( you can see what test fail on circleCI ).

Hope you'll find a solution !

Good luck !

**Comment by alexislefebvre** [comment]
@Yoann-TYT It looks like the `(?!.*Tests)` part in the regex remove the files in `Tests` from the list of files. But these files are necessary during tests.

**Comment by lenybernard** [comment]
replaced by #1025

**Pull request closed without merging**
