### PR TITLE
See #763: Blog > Add slug field on article creation form

### PR DESCRIPTION
**Pull request by alexislefebvre**
## Type
Feature

## Purpose
Fix the issue #763 by adding the slug field on article creation form.

### CODE REVIEW

**Comment by alexislefebvre** [comment]
I have to remove the asterisk (`*`) from the *slug* form. There is no error when the slug is empty, the article is created succesfully.

And tests have to be added.

**Comment by alexislefebvre** [comment]
The tests finally passed. Please wait before merging this, I'll clean the last commits.

**Comment by paulandrieux** [comment]
Still some CS to fix please

**Comment by alexislefebvre** [comment]
Style CI reports this error:

> We were unable to access the repo or commit to analyze it.
> 
> It is possible that the commit was deleted from GitHub before we had time to analyze it.

Source: https://styleci.io/analyses/XNLene

**Pull request merged**
